"""
InDE MVP v5.1b.0 - DOCX Renderer

Renders styled ITD to Microsoft Word document via python-docx.
Preserves v4.3 organic visual identity through custom styles.
Business-ready formatting with headers, footers, and proper typography.

2026 Yul Williams | InDEVerse, Incorporated
"""

from typing import Dict, Optional, Any, List
import logging
from io import BytesIO

from .base_renderer import BaseRenderer

logger = logging.getLogger(__name__)


class DOCXRenderer(BaseRenderer):
    """
    Renders styled ITD to DOCX format.

    Uses python-docx to create professionally formatted Word documents
    with custom styles matching the v4.3 organic visual identity.
    """

    def __init__(self):
        """Initialize and check python-docx availability."""
        self._docx_available = self._check_docx()

    def _check_docx(self) -> bool:
        """Check if python-docx is available."""
        try:
            import docx  # noqa: F401
            return True
        except ImportError:
            logger.warning(
                "python-docx not available. DOCX export will be disabled."
            )
            return False

    @property
    def content_type(self) -> str:
        return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    def render(
        self,
        styled_itd: Dict[str, Any],
        template_data: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """
        Render the styled ITD as DOCX.

        Args:
            styled_itd: The styled ITD document with layer ordering
            template_data: Optional populated template fields

        Returns:
            DOCX content as bytes
        """
        if not self._docx_available:
            raise RuntimeError(
                "python-docx is required for DOCX export. "
                "Install with: pip install python-docx"
            )

        try:
            return self._render_document(styled_itd, template_data)
        except Exception as e:
            logger.error(f"DOCX rendering failed: {e}")
            raise

    def _render_document(
        self,
        styled_itd: Dict[str, Any],
        template_data: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """Create the Word document."""
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.style import WD_STYLE_TYPE

        # Create document
        doc = Document()

        # Apply custom styles
        self._apply_styles(doc)

        # Title
        pursuit_title = self._get_pursuit_title(styled_itd)
        title = doc.add_heading(pursuit_title, level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle with style and date
        style_name = self._get_style_display_name(styled_itd)
        date = self._get_generated_date()
        subtitle = doc.add_paragraph(f"{style_name} | Generated {date} by InDE")
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_format = subtitle.runs[0].font
        subtitle_format.italic = True
        subtitle_format.color.rgb = RGBColor(0x70, 0x70, 0x80)

        # Horizontal line
        doc.add_paragraph("─" * 60)

        # Style opening
        style_opening = styled_itd.get("style_opening", "")
        if style_opening:
            opening_para = doc.add_paragraph(style_opening)
            opening_para.runs[0].font.size = Pt(12)
            opening_para.runs[0].font.italic = True
            doc.add_paragraph("─" * 60)

        # Render layers in style order
        layer_ordering = styled_itd.get(
            "layer_ordering",
            ["thesis_statement", "narrative_arc", "evidence_architecture",
             "coachs_perspective", "pattern_connections", "forward_projection"]
        )

        layer_titles = {
            "thesis_statement": "Your Innovation Thesis",
            "evidence_architecture": "Evidence Architecture",
            "narrative_arc": "Narrative Arc",
            "coachs_perspective": "Coach's Perspective",
            "pattern_connections": "Pattern Connections",
            "forward_projection": "Forward Projection",
        }

        for layer_key in layer_ordering:
            layer = styled_itd.get(layer_key)
            if layer:
                title = layer_titles.get(layer_key, layer_key.replace("_", " ").title())
                self._render_layer_section(doc, title, layer_key, layer)

        # Template section
        if template_data:
            self._render_template_section(doc, template_data)

        # Footer
        doc.add_paragraph("─" * 60)
        footer = doc.add_paragraph(
            "This document was generated by InDE — Innovation Thesis Intelligence"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.italic = True
        footer.runs[0].font.color.rgb = RGBColor(0x70, 0x70, 0x80)

        # Save to bytes
        buffer = BytesIO()
        doc.save(buffer)
        return buffer.getvalue()

    def _apply_styles(self, doc) -> None:
        """Apply custom styles matching v4.3 organic visual identity."""
        from docx.shared import Pt, RGBColor
        from docx.enum.style import WD_STYLE_TYPE

        # Style the default heading styles
        styles = doc.styles

        # Heading 1 - Primary green
        if 'Heading 1' in styles:
            h1 = styles['Heading 1']
            h1.font.color.rgb = RGBColor(0x2d, 0x4a, 0x3e)
            h1.font.size = Pt(24)
            h1.font.bold = True

        # Heading 2 - Primary green
        if 'Heading 2' in styles:
            h2 = styles['Heading 2']
            h2.font.color.rgb = RGBColor(0x2d, 0x4a, 0x3e)
            h2.font.size = Pt(18)
            h2.font.bold = True

        # Heading 3 - Secondary text
        if 'Heading 3' in styles:
            h3 = styles['Heading 3']
            h3.font.color.rgb = RGBColor(0x4a, 0x4a, 0x5c)
            h3.font.size = Pt(14)
            h3.font.bold = True

        # Normal text
        if 'Normal' in styles:
            normal = styles['Normal']
            normal.font.name = 'Georgia'
            normal.font.size = Pt(11)
            normal.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    def _render_layer_section(
        self,
        doc,
        title: str,
        layer_key: str,
        layer: Dict[str, Any]
    ) -> None:
        """Render a layer section to the document."""
        from docx.shared import Pt, RGBColor

        # Section heading
        doc.add_heading(title, level=1)

        # Render based on layer type
        if layer_key == "thesis_statement":
            self._render_thesis_docx(doc, layer)
        elif layer_key == "evidence_architecture":
            self._render_evidence_docx(doc, layer)
        elif layer_key == "narrative_arc":
            self._render_narrative_docx(doc, layer)
        elif layer_key == "coachs_perspective":
            self._render_coach_docx(doc, layer)
        elif layer_key == "pattern_connections":
            self._render_patterns_docx(doc, layer)
        elif layer_key == "forward_projection":
            self._render_projection_docx(doc, layer)
        else:
            # Generic content
            content = self._get_layer_content(layer)
            doc.add_paragraph(content)

        # Add spacing
        doc.add_paragraph()

    def _render_thesis_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render thesis statement layer."""
        from docx.shared import Pt, RGBColor

        thesis_text = layer.get("thesis_text", "")
        if thesis_text:
            para = doc.add_paragraph(thesis_text)
            para.runs[0].font.italic = True
            para.runs[0].font.size = Pt(14)

        confidence = layer.get("confidence_score", 0)
        if confidence > 0:
            conf_para = doc.add_paragraph()
            run = conf_para.add_run(f"Confidence Level: {confidence:.0%}")
            run.font.bold = True
            run.font.color.rgb = RGBColor(0x7f, 0xb0, 0x69)

    def _render_evidence_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render evidence architecture layer."""
        from docx.shared import Pt

        # Confidence journey
        initial = layer.get("initial_confidence", 0)
        final = layer.get("final_confidence", 0)
        delta = layer.get("confidence_delta", 0)

        if initial > 0 or final > 0:
            doc.add_heading("Confidence Journey", level=2)
            doc.add_paragraph(f"Started: {initial:.0%}")
            doc.add_paragraph(f"Ended: {final:.0%}")
            sign = '+' if delta > 0 else ''
            doc.add_paragraph(f"Change: {sign}{delta:.0%}")

        # Pivots
        pivots = layer.get("pivots", [])
        if pivots:
            doc.add_heading("Direction Changes", level=2)
            for pivot in pivots:
                pivot_type = pivot.get("pivot_type", "Pivot")
                description = pivot.get("description", "")
                para = doc.add_paragraph()
                run = para.add_run(f"{pivot_type}: ")
                run.font.bold = True
                para.add_run(description)

    def _render_narrative_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render narrative arc layer."""
        from docx.shared import Pt

        # Opening hook
        opening = layer.get("opening_hook", "")
        if opening:
            para = doc.add_paragraph(opening)
            para.runs[0].font.italic = True

        # Acts
        acts = layer.get("acts", [])
        for act in acts:
            title = act.get("title", act.get("act_type", "Act"))
            content = act.get("content", "")
            doc.add_heading(title, level=2)
            doc.add_paragraph(content)

        # Closing reflection
        closing = layer.get("closing_reflection", "")
        if closing:
            para = doc.add_paragraph(closing)
            para.runs[0].font.italic = True

    def _render_coach_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render coach's perspective layer."""
        from docx.shared import Pt, Inches

        # Overall reflection
        reflection = layer.get("overall_reflection", "")
        if reflection:
            doc.add_paragraph(reflection)

        # Moments
        moments = layer.get("moments", [])
        for moment in moments:
            moment_type = moment.get("moment_type", "Moment")
            quote = moment.get("coach_quote", "")
            impact = moment.get("impact", "")

            # Moment type header
            para = doc.add_paragraph()
            run = para.add_run(moment_type)
            run.font.bold = True

            # Quote as indented paragraph
            if quote:
                quote_para = doc.add_paragraph(quote)
                quote_para.paragraph_format.left_indent = Inches(0.5)
                quote_para.runs[0].font.italic = True

            # Impact
            if impact:
                impact_para = doc.add_paragraph(f"Impact: {impact}")
                impact_para.runs[0].font.italic = True

    def _render_patterns_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render pattern connections layer."""
        content = layer.get("content", layer)

        opening = content.get("opening", "")
        if opening:
            doc.add_paragraph(opening)

        # Within pursuit patterns
        within = content.get("within_pursuit", {})
        if within and within.get("narrative"):
            doc.add_heading("Within This Pursuit", level=2)
            doc.add_paragraph(within["narrative"])

        # Cross-pursuit patterns
        cross = content.get("cross_pursuit", {})
        if cross and cross.get("narrative"):
            doc.add_heading("Connections to Other Pursuits", level=2)
            doc.add_paragraph(cross["narrative"])

        # Synthesis
        synthesis = content.get("synthesis", "")
        if synthesis:
            para = doc.add_paragraph(synthesis)
            para.runs[0].font.italic = True

    def _render_projection_docx(self, doc, layer: Dict[str, Any]) -> None:
        """Render forward projection layer."""
        from docx.shared import RGBColor

        content = layer.get("content", layer)

        # Synthesis statement
        synthesis = content.get("synthesis_statement", "")
        if synthesis:
            doc.add_paragraph(synthesis)

        # Horizons
        horizons = content.get("horizons", {})
        horizon_names = {
            "day_90": "90-Day Horizon",
            "day_180": "180-Day Horizon",
            "day_365": "One-Year Horizon",
        }

        for key in ["day_90", "day_180", "day_365"]:
            horizon = horizons.get(key)
            if horizon:
                name = horizon_names.get(key, key)
                doc.add_heading(name, level=2)

                narrative = horizon.get("narrative", "")
                if narrative:
                    doc.add_paragraph(narrative)

                confidence = horizon.get("confidence", 0)
                if confidence > 0:
                    conf_para = doc.add_paragraph(f"Confidence: {confidence:.0%}")
                    conf_para.runs[0].font.italic = True
                    conf_para.runs[0].font.color.rgb = RGBColor(0x70, 0x70, 0x80)

                actions = horizon.get("success_correlated_actions", [])
                if actions:
                    doc.add_paragraph("Recommended Actions:")
                    for action in actions:
                        doc.add_paragraph(f"• {action}")

    def _render_template_section(
        self,
        doc,
        template_data: Dict[str, Any]
    ) -> None:
        """Render template section."""
        from docx.shared import RGBColor

        doc.add_heading("Supporting Documentation", level=1)

        for field_name, value in template_data.items():
            display_name = field_name.replace("_", " ").title()
            doc.add_heading(display_name, level=2)

            if value and str(value).startswith("[") and str(value).endswith("]"):
                # Partial field
                warning_para = doc.add_paragraph()
                warning_run = warning_para.add_run("This dimension is still forming.")
                warning_run.font.color.rgb = RGBColor(0x8a, 0x6c, 0x3d)
                warning_run.font.italic = True

                content_para = doc.add_paragraph(str(value)[1:-1])
                content_para.runs[0].font.italic = True
            else:
                doc.add_paragraph(str(value) if value else "Not available")
