"""
InDE MVP v5.1b.0 - Markdown Renderer

Renders styled ITD layers as structured Markdown with H1/H2/H3 hierarchy.
Template fields rendered as a structured section with field-level labels.
Partial fields annotated with cautionary note.

2026 Yul Williams | InDEVerse, Incorporated
"""

from typing import Dict, Optional, Any
from .base_renderer import BaseRenderer


class MarkdownRenderer(BaseRenderer):
    """
    Renders styled ITD to structured Markdown.

    Output structure:
    - Title with style and date
    - Style opening paragraph
    - ITD layers in style order
    - Template section (if applicable)
    - Footer
    """

    @property
    def content_type(self) -> str:
        return "text/markdown"

    def render(
        self,
        styled_itd: Dict[str, Any],
        template_data: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Render the styled ITD as Markdown."""
        parts = []

        # Title
        pursuit_title = self._get_pursuit_title(styled_itd)
        style_name = self._get_style_display_name(styled_itd)
        date = self._get_generated_date()

        parts.append(f"# {pursuit_title} — Innovation Thesis")
        parts.append(f"*{style_name} | Generated {date} by InDE*")
        parts.append("")
        parts.append("---")
        parts.append("")

        # Style opening
        style_opening = styled_itd.get("style_opening", "")
        if style_opening:
            parts.append(style_opening)
            parts.append("")
            parts.append("---")
            parts.append("")

        # Render layers in style order
        layer_ordering = styled_itd.get(
            "layer_ordering",
            ["thesis_statement", "narrative_arc", "evidence_architecture",
             "coachs_perspective", "pattern_connections", "forward_projection"]
        )

        layer_titles = {
            "thesis_statement": "Your Innovation Thesis",
            "evidence_architecture": "Evidence Architecture",
            "narrative_arc": "Narrative Arc",
            "coachs_perspective": "Coach's Perspective",
            "pattern_connections": "Pattern Connections",
            "forward_projection": "Forward Projection",
        }

        for layer_key in layer_ordering:
            layer = styled_itd.get(layer_key)
            if layer:
                title = layer_titles.get(layer_key, layer_key.replace("_", " ").title())
                parts.append(f"## {title}")
                parts.append("")
                parts.append(self._render_layer(layer_key, layer))
                parts.append("")
                parts.append("---")
                parts.append("")

        # Template section (if provided)
        if template_data:
            parts.append("## Supporting Documentation")
            parts.append("")
            for field_name, value in template_data.items():
                display_name = field_name.replace("_", " ").title()
                parts.append(f"### {display_name}")
                parts.append("")

                # Check if this is a fallback/partial field
                if value and value.startswith("[") and value.endswith("]"):
                    parts.append(f"> ⚠ This dimension is still forming.")
                    parts.append("")
                    parts.append(f"*{value[1:-1]}*")
                else:
                    parts.append(value if value else "*Not available*")
                parts.append("")

        # Footer
        parts.append("---")
        parts.append("")
        parts.append("*This document was generated by InDE — Innovation Thesis Intelligence*")
        parts.append("*All content derived from pursuit data — no manual entry required*")

        return "\n".join(parts)

    def _render_layer(self, layer_key: str, layer: Dict[str, Any]) -> str:
        """Render a specific layer based on its type."""
        if layer_key == "thesis_statement":
            return self._render_thesis(layer)
        elif layer_key == "evidence_architecture":
            return self._render_evidence(layer)
        elif layer_key == "narrative_arc":
            return self._render_narrative(layer)
        elif layer_key == "coachs_perspective":
            return self._render_coach(layer)
        elif layer_key == "pattern_connections":
            return self._render_patterns(layer)
        elif layer_key == "forward_projection":
            return self._render_projection(layer)
        else:
            return self._get_layer_content(layer)

    def _render_thesis(self, layer: Dict[str, Any]) -> str:
        """Render thesis statement layer."""
        parts = []

        # Get thesis text
        thesis_text = layer.get("thesis_text", "")
        if thesis_text:
            parts.append(f"*{thesis_text}*")

        # Confidence (if available)
        confidence = layer.get("confidence_score", 0)
        if confidence > 0:
            parts.append("")
            parts.append(f"**Confidence Level:** {confidence:.0%}")

        return "\n".join(parts)

    def _render_evidence(self, layer: Dict[str, Any]) -> str:
        """Render evidence architecture layer."""
        parts = []

        # Confidence trajectory
        trajectory = layer.get("confidence_trajectory", [])
        if trajectory:
            parts.append("### Confidence Journey")
            parts.append("")
            initial = layer.get("initial_confidence", 0)
            final = layer.get("final_confidence", 0)
            delta = layer.get("confidence_delta", 0)
            parts.append(f"- Started: {initial:.0%}")
            parts.append(f"- Ended: {final:.0%}")
            parts.append(f"- Change: {'+' if delta > 0 else ''}{delta:.0%}")
            parts.append("")

        # Tested assumptions
        assumptions = layer.get("tested_assumptions", [])
        if assumptions:
            parts.append("### Validated Assumptions")
            parts.append("")
            for assumption in assumptions[:5]:  # Limit to 5
                if isinstance(assumption, dict):
                    text = assumption.get("assumption_text", str(assumption))
                else:
                    text = str(assumption)
                parts.append(f"- {text}")
            parts.append("")

        # Pivots
        pivots = layer.get("pivots", [])
        if pivots:
            parts.append("### Direction Changes")
            parts.append("")
            for pivot in pivots:
                pivot_type = pivot.get("pivot_type", "Pivot")
                description = pivot.get("description", "")
                parts.append(f"**{pivot_type}:** {description}")
                parts.append("")

        return "\n".join(parts)

    def _render_narrative(self, layer: Dict[str, Any]) -> str:
        """Render narrative arc layer."""
        parts = []

        # Opening hook
        opening = layer.get("opening_hook", "")
        if opening:
            parts.append(f"*{opening}*")
            parts.append("")

        # Acts
        acts = layer.get("acts", [])
        for act in acts:
            title = act.get("title", act.get("act_type", "Act"))
            content = act.get("content", "")
            parts.append(f"### {title}")
            parts.append("")
            parts.append(content)
            parts.append("")

        # Closing reflection
        closing = layer.get("closing_reflection", "")
        if closing:
            parts.append(f"*{closing}*")

        return "\n".join(parts)

    def _render_coach(self, layer: Dict[str, Any]) -> str:
        """Render coach's perspective layer."""
        parts = []

        # Overall reflection
        reflection = layer.get("overall_reflection", "")
        if reflection:
            parts.append(reflection)
            parts.append("")

        # Moments
        moments = layer.get("moments", [])
        for moment in moments:
            moment_type = moment.get("moment_type", "Moment")
            quote = moment.get("coach_quote", "")
            impact = moment.get("impact", "")

            parts.append(f"**{moment_type}**")
            parts.append("")
            parts.append(f"> {quote}")
            if impact:
                parts.append("")
                parts.append(f"*Impact: {impact}*")
            parts.append("")

        return "\n".join(parts)

    def _render_patterns(self, layer: Dict[str, Any]) -> str:
        """Render pattern connections layer."""
        parts = []

        # Try to get content from nested structure
        content = layer.get("content", layer)

        opening = content.get("opening", "")
        if opening:
            parts.append(opening)
            parts.append("")

        # Within pursuit patterns
        within = content.get("within_pursuit", {})
        if within and within.get("narrative"):
            parts.append("### Within This Pursuit")
            parts.append("")
            parts.append(within["narrative"])
            parts.append("")

        # Cross-pursuit patterns
        cross = content.get("cross_pursuit", {})
        if cross and cross.get("narrative"):
            parts.append("### Connections to Other Pursuits")
            parts.append("")
            parts.append(cross["narrative"])
            parts.append("")

        # Federation patterns
        federation = content.get("federation", {})
        if federation and federation.get("narrative"):
            parts.append("### Cross-Organization Intelligence")
            parts.append("")
            parts.append(federation["narrative"])
            parts.append("")

        # Synthesis
        synthesis = content.get("synthesis", "")
        if synthesis:
            parts.append(f"*{synthesis}*")

        return "\n".join(parts)

    def _render_projection(self, layer: Dict[str, Any]) -> str:
        """Render forward projection layer."""
        parts = []

        # Try to get content from nested structure
        content = layer.get("content", layer)

        # Synthesis statement
        synthesis = content.get("synthesis_statement", "")
        if synthesis:
            parts.append(synthesis)
            parts.append("")

        # Horizons
        horizons = content.get("horizons", {})
        horizon_names = {
            "day_90": "90-Day Horizon",
            "day_180": "180-Day Horizon",
            "day_365": "One-Year Horizon",
        }

        for key in ["day_90", "day_180", "day_365"]:
            horizon = horizons.get(key)
            if horizon:
                name = horizon_names.get(key, key)
                parts.append(f"### {name}")
                parts.append("")

                narrative = horizon.get("narrative", "")
                if narrative:
                    parts.append(narrative)
                    parts.append("")

                confidence = horizon.get("confidence", 0)
                if confidence > 0:
                    parts.append(f"*Confidence: {confidence:.0%}*")
                    parts.append("")

                actions = horizon.get("success_correlated_actions", [])
                if actions:
                    parts.append("**Recommended Actions:**")
                    for action in actions:
                        parts.append(f"- {action}")
                    parts.append("")

        return "\n".join(parts)
