"""
InDE MVP v5.1b.0 - PDF Renderer

Renders styled ITD to PDF via WeasyPrint.
Sources HTML from HTMLRenderer for consistent styling.
Print-optimized with page breaks and headers/footers.

2026 Yul Williams | InDEVerse, Incorporated
"""

from typing import Dict, Optional, Any
import logging
from io import BytesIO

from .base_renderer import BaseRenderer
from .html_renderer import HTMLRenderer

logger = logging.getLogger(__name__)


class PDFRenderer(BaseRenderer):
    """
    Renders styled ITD to PDF format.

    Uses WeasyPrint to convert HTML to PDF, preserving the v4.3 organic
    visual identity. Includes print-optimized page breaks and footers.
    """

    def __init__(self):
        """Initialize with HTML renderer for source generation."""
        self._html_renderer = HTMLRenderer()
        self._weasyprint_available = self._check_weasyprint()

    def _check_weasyprint(self) -> bool:
        """Check if WeasyPrint is available."""
        try:
            import weasyprint  # noqa: F401
            return True
        except ImportError:
            logger.warning(
                "WeasyPrint not available. PDF export will use fallback."
            )
            return False

    @property
    def content_type(self) -> str:
        return "application/pdf"

    def render(
        self,
        styled_itd: Dict[str, Any],
        template_data: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """
        Render the styled ITD as PDF.

        Args:
            styled_itd: The styled ITD document with layer ordering
            template_data: Optional populated template fields

        Returns:
            PDF content as bytes
        """
        # Generate HTML source
        html_content = self._html_renderer.render(styled_itd, template_data)

        if not self._weasyprint_available:
            return self._fallback_pdf(html_content)

        try:
            return self._render_with_weasyprint(html_content)
        except Exception as e:
            logger.error(f"WeasyPrint rendering failed: {e}")
            return self._fallback_pdf(html_content)

    def _render_with_weasyprint(self, html_content: str) -> bytes:
        """Render HTML to PDF using WeasyPrint."""
        from weasyprint import HTML, CSS

        # Additional print-specific CSS
        print_css = CSS(string="""
            @page {
                size: letter;
                margin: 2cm;
                @bottom-center {
                    content: "Generated by InDE — Innovation Thesis Intelligence | Page " counter(page) " of " counter(pages);
                    font-size: 10px;
                    color: #707080;
                }
            }

            body {
                font-size: 11pt;
            }

            .layer-section {
                break-inside: avoid;
                page-break-inside: avoid;
            }

            h2 {
                break-after: avoid;
                page-break-after: avoid;
            }

            .horizon {
                break-inside: avoid;
                page-break-inside: avoid;
            }

            .moment {
                break-inside: avoid;
                page-break-inside: avoid;
            }
        """)

        # Create PDF
        html_doc = HTML(string=html_content)
        pdf_buffer = BytesIO()
        html_doc.write_pdf(pdf_buffer, stylesheets=[print_css])

        return pdf_buffer.getvalue()

    def _fallback_pdf(self, html_content: str) -> bytes:
        """
        Generate a minimal PDF when WeasyPrint is unavailable.

        Returns a simple text-based PDF with basic formatting.
        """
        # Extract text content from HTML for fallback
        import re
        text = re.sub(r'<[^>]+>', '', html_content)
        text = re.sub(r'\s+', ' ', text).strip()

        # Generate minimal PDF structure
        pdf_content = self._create_minimal_pdf(text)
        return pdf_content

    def _create_minimal_pdf(self, text: str) -> bytes:
        """
        Create a minimal valid PDF with text content.

        This is a fallback when WeasyPrint is not available.
        The PDF structure follows PDF 1.4 specification.
        """
        # Escape special characters for PDF
        text = text.replace('\\', '\\\\')
        text = text.replace('(', '\\(')
        text = text.replace(')', '\\)')

        # Truncate if too long for single page
        if len(text) > 4000:
            text = text[:4000] + "..."

        # Build PDF structure
        objects = []

        # Object 1: Catalog
        objects.append(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

        # Object 2: Pages
        objects.append(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")

        # Object 3: Page
        objects.append(
            b"3 0 obj\n<< /Type /Page /Parent 2 0 R "
            b"/MediaBox [0 0 612 792] /Contents 4 0 R "
            b"/Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n"
        )

        # Object 4: Content stream
        content_stream = (
            f"BT\n/F1 11 Tf\n72 720 Td\n12 TL\n({text[:500]}) Tj\nET"
        ).encode('latin-1', errors='replace')

        stream_length = len(content_stream)
        objects.append(
            f"4 0 obj\n<< /Length {stream_length} >>\nstream\n".encode() +
            content_stream +
            b"\nendstream\nendobj\n"
        )

        # Object 5: Font
        objects.append(
            b"5 0 obj\n<< /Type /Font /Subtype /Type1 "
            b"/BaseFont /Helvetica >>\nendobj\n"
        )

        # Build PDF
        pdf = b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"

        xref_positions = []
        for obj in objects:
            xref_positions.append(len(pdf))
            pdf += obj

        # Cross-reference table
        xref_start = len(pdf)
        pdf += b"xref\n"
        pdf += f"0 {len(objects) + 1}\n".encode()
        pdf += b"0000000000 65535 f \n"
        for pos in xref_positions:
            pdf += f"{pos:010d} 00000 n \n".encode()

        # Trailer
        pdf += b"trailer\n"
        pdf += f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n".encode()
        pdf += b"startxref\n"
        pdf += f"{xref_start}\n".encode()
        pdf += b"%%EOF\n"

        return pdf
